name: CD

on:
  workflow_run:
    workflows: ["CI"]
    branches: [cloud]
    types: [completed]

env:
  IMAGE_NAME: registry.cn-chengdu.aliyuncs.com/zrqpublic/fn-monitor
  CONTAINER: fn-monitor

jobs:
  deploy:
    runs-on: jump-zrq
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Pull new image
        run: docker pull ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Stop & remove old container
        run: |
          docker stop ${{ env.CONTAINER }} || true
          docker rm   ${{ env.CONTAINER }} || true

      - name: Start new container
        run: |
          docker run -d --restart=unless-stopped \
            -p 7733:7733 \
            -v /tmp:/tmp:ro \
            --name ${{ env.CONTAINER }} \
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Health check
        run: |
          for i in {1..10}; do
            nc -z 127.0.0.1 7733 && echo 'Service UP' && exit 0
            sleep 2
          done
          echo 'Health check failed' && exit 1