name: CD

on:
  push:
    branches: [cloud]

env:
  APP_NAME: fn-monitor
  ALIYUN_REGISTRY: registry.cn-chengdu.aliyuncs.com
  ALIYUN_NAMESPACE: zrqpublic/fn-monitor
  IMAGE_NAME: registry.cn-chengdu.aliyuncs.com/zrqpublic/fn-monitor
jobs:
  docker-push:
    name: Build & Push to ACR
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - uses: actions/checkout@v4
      # ---------- 3. 检查 Secrets 是否非空（不暴露内容） ----------
      
      - name: Check ACR Secrets
        run: |
          if [ -z "${{ secrets.ACR_USERNAME }}" ] || [ -z "${{ secrets.ACR_PASSWORD }}" ]; then
            echo "ACR_USERNAME or ACR_PASSWORD is not set. Exiting."
            exit 1
          fi
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          # username: '天有多云'
          # password: 'zhang!@12345'
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}          

      # 2. 构建并推送
      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
            ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

          #213123
  # deploy:
  #   name: Deploy to K8s
  #   needs: docker-push
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     # 3. 生成新版本的 deployment patch
  #     - run: |
  #         curl -s "https://raw.githubusercontent.com/kubernetes-sigs/kustomize/master/hack/install_kustomize.sh" | bash
  #         sudo mv kustomize /usr/local/bin/
  #         cd k8s/overlays/prod
  #         kustomize edit set image ${{ env.APP_NAME }}=${{ env.IMAGE_NAME }}:${{ github.sha }}

  #     # 4. 部署（需 KUBECONFIG 秘钥）
  #     - uses: azure/k8s-deploy@v5
  #       with:
  #         manifests: |
  #           k8s/overlays/prod
  #         kubectl-version: 'latest'
  #         kubeconfig: ${{ secrets.KUBECONFIG }}