name: CI

on:
  push:
    branches: [cloud]

env:
  APP_NAME: fn-monitor
  ALIYUN_REGISTRY: registry.cn-chengdu.aliyuncs.com
  ALIYUN_NAMESPACE: zrqpublic
  IMAGE_NAME: registry.cn-chengdu.aliyuncs.com/zrqpublic/fn-monitor

jobs:
  docker-push:
    name: Build & Push to ACR
    runs-on: ubuntu-latest

    environment: dev

    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ${{ env.ALIYUN_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}          

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:latest
          cache-from: type=gha

#          